POST http://localhost:3000/user/login
Content-Type: application/json

{
   "username":"eric",
   "password":"1234"
}

###
POST http://localhost:3000/user/create-user
Content-Type: application/json

{
   "username":"abebe",
   "password":"1234"
}


###
POST http://localhost:3000/user/logout
Content-Type: application/json

{
   "id":"3"
}



###
GET http://localhost:3000/music
Authorization: "www"

###
GET http://localhost:3000/music/3
Authorization: "www"

###
GET http://localhost:3000/music/playlist
Authorization: "1716411376848_eric"


###
POST http://localhost:3000/music/playlist
Content-Type: application/json
Authorization: "1716411376848_eric"

{

    "id": 5
    
}

###
DELETE http://localhost:3000/music/playlist/2
Authorization: "www"